// autogenerated by reconstant - do not edit!

// constants
pub const SOME_CONSTANT: &str = "this is a constant string";
pub const OTHER_CONSTANT: i32 = 42;

// enums
pub enum SomeEnum {
	A=0,
	B=1,
	C=2,
}
pub enum OtherEnum {
	FOO=0,
	BAR=1,
	BAZ=2,
	QUUX=5,
	CORGE=6,
}
