// autogenerated by reconstant - do not edit!
public final class Constants {

	// constants
	public static final String SOME_CONSTANT = "this is a constant string";
	public static final int OTHER_CONSTANT = 42;

	// enums
	public enum SomeEnum {
		A(0),
		B(1),
		C(2);
		private final int value;
		SomeEnum(int value) {
			this.value = value;
		}
		public int getValue() {
			return this.value;
		}
	}

	public enum OtherEnum {
		FOO(0),
		BAR(1),
		BAZ(2),
		QUUX(5),
		CORGE(6);
		private final int value;
		OtherEnum(int value) {
			this.value = value;
		}
		public int getValue() {
			return this.value;
		}
	}

}