// autogenerated by reconstant - do not edit!
library constants;


// constants
const someConstant = "this is a constant string";
const otherConstant = 42;

// enums
enum SomeEnum {
	a(0),
	b(1),
	c(2);

	final int code;
	const SomeEnum(this.code);
}
enum OtherEnum {
	foo(0),
	bar(1),
	baz(2),
	quux(5),
	corge(6);

	final int code;
	const OtherEnum(this.code);
}
