// autogenerated by reconstant - do not edit!
#ifndef AUTOGENERATED_EXAMPLES_CONSTANTS_H
#define AUTOGENERATED_EXAMPLES_CONSTANTS_H

// constants
#define SOME_CONSTANT "this is a constant string"
#define OTHER_CONSTANT 42

// enums
typedef enum {
	SOME_ENUM_A=0,
	SOME_ENUM_B=1,
	SOME_ENUM_C=2,
}  SomeEnum;
typedef enum {
	OTHER_ENUM_FOO=0,
	OTHER_ENUM_BAR=1,
	OTHER_ENUM_BAZ=2,
	OTHER_ENUM_QUUX=5,
	OTHER_ENUM_CORGE=6,
}  OtherEnum;

#endif /* AUTOGENERATED_EXAMPLES_CONSTANTS_H */